// flow-typed signature: bda79db7a3ba843af254c23d4434f7f7
// flow-typed version: <<STUB>>/csv-parse_v4.15.3/flow_v0.146.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-parse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-parse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csv-parse/lib/browser' {
  declare module.exports: any;
}

declare module 'csv-parse/lib/browser/sync' {
  declare module.exports: any;
}

declare module 'csv-parse/lib/es5' {
  declare module.exports: any;
}

declare module 'csv-parse/lib/es5/ResizeableBuffer' {
  declare module.exports: any;
}

declare module 'csv-parse/lib/es5/sync' {
  declare module.exports: any;
}

declare module 'csv-parse/lib' {
  declare module.exports: any;
}

declare module 'csv-parse/lib/ResizeableBuffer' {
  declare module.exports: any;
}

declare module 'csv-parse/lib/sync' {
  declare module.exports: string => Array<Array<string>>;
}

// Filename aliases
declare module 'csv-parse/lib/browser/index' {
  declare module.exports: $Exports<'csv-parse/lib/browser'>;
}
declare module 'csv-parse/lib/browser/index.js' {
  declare module.exports: $Exports<'csv-parse/lib/browser'>;
}
declare module 'csv-parse/lib/browser/sync.js' {
  declare module.exports: $Exports<'csv-parse/lib/browser/sync'>;
}
declare module 'csv-parse/lib/es5/index' {
  declare module.exports: $Exports<'csv-parse/lib/es5'>;
}
declare module 'csv-parse/lib/es5/index.js' {
  declare module.exports: $Exports<'csv-parse/lib/es5'>;
}
declare module 'csv-parse/lib/es5/ResizeableBuffer.js' {
  declare module.exports: $Exports<'csv-parse/lib/es5/ResizeableBuffer'>;
}
declare module 'csv-parse/lib/es5/sync.js' {
  declare module.exports: $Exports<'csv-parse/lib/es5/sync'>;
}
declare module 'csv-parse/lib/index' {
  declare module.exports: $Exports<'csv-parse/lib'>;
}
declare module 'csv-parse/lib/index.js' {
  declare module.exports: $Exports<'csv-parse/lib'>;
}
declare module 'csv-parse/lib/ResizeableBuffer.js' {
  declare module.exports: $Exports<'csv-parse/lib/ResizeableBuffer'>;
}
declare module 'csv-parse/lib/sync.js' {
  declare module.exports: $Exports<'csv-parse/lib/sync'>;
}
