// flow-typed signature: 2b442632c1ced8ab724602bf207b89e8
// flow-typed version: <<STUB>>/papaparse_v5.3.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'papaparse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'papaparse' {
  declare type ParseResults = {|
    data: Array<Array<string>>,
  |};

  declare module.exports: {|
    parse(csvString: string, config?: {...}): ParseResults,
  |};
}
