name: Release
on:
  push:
    tags:
      - v*

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run Yarn
        run: yarn
      - name: Run checks
        run: yarn run check-all
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
